const defaultQuestions = [
    {
        id: 1,
        title: 'Which service are you interested in?',
        active: true,
        options: [
            {
                id: 1,
                title: 'Custom Software Development',
                subtitle: null,
                icon: '/assets/customSoftwareIcon.svg',
                alt: 'three floating screen',
                selected: false,
                cost: 0,
            },
            {
                id: 2,
                title: 'Android/IOS App Development',
                subtitle: null,
                icon: '/assets/mobileIcon.svg',
                alt: 'phones and tablets',
                selected: false,
                cost: 0,
            },
            {
                id: 3,
                title: 'Website Development',
                subtitle: null,
                icon: '/assets/websiteIcon.svg',
                alt: 'computer',
                selected: false,
                cost: 0,
            },
        ],
    },
];

const softwareQuestions = [
    { ...defaultQuestions[0], active: false },
    {
        id: 2,
        title: 'Which platforms do you need supported?',
        subtitle: 'Select all that apply.',
        options: [
            {
                id: 1,
                title: 'Web Application',
                subtitle: null,
                icon: '/assets/websiteIcon.svg',
                iconAlt: 'computer outline',
                selected: false,
                cost: 100,
            },
            {
                id: 2,
                title: 'iOS Application',
                subtitle: null,
                icon: '/assets/iphone.svg',
                iconAlt: 'outline of iphone',
                selected: false,
                cost: 100,
            },
            {
                id: 3,
                title: 'Android Application',
                subtitle: null,
                icon: '/assets/android.svg',
                iconAlt: 'outlines of android phone',
                selected: false,
                cost: 100,
            },
        ],
        active: true,
    },
    {
        id: 3,
        title: 'Which features do you expect to use?',
        subtitle: 'Select all that apply.',
        options: [
            {
                id: 1,
                title: 'Photo/Video',
                subtitle: null,
                icon: '/assets/camera.svg',
                iconAlt: 'camera outline',
                selected: false,
                cost: 25,
            },
            {
                id: 2,
                title: 'GPS',
                subtitle: null,
                icon: '/assets/gps.svg',
                iconAlt: 'gps pin',
                selected: false,
                cost: 25,
            },
            {
                id: 3,
                title: 'File Transfer',
                subtitle: null,
                icon: '/assets/upload.svg',
                iconAlt: 'outline of cloud with arrow pointing up',
                selected: false,
                cost: 25,
            },
        ],
        active: false,
    },
    {
        id: 4,
        title: 'Which features do you expect to use?',
        subtitle: 'Select all that apply.',
        options: [
            {
                id: 1,
                title: 'Users/Authentication',
                subtitle: null,
                icon: '/assets/users.svg',
                iconAlt: 'outline of a person with a plus sign',
                selected: false,
                cost: 25,
            },
            {
                id: 2,
                title: 'Biometrics',
                subtitle: null,
                icon: '/assets/biometrics.svg',
                iconAlt: 'fingerprint',
                selected: false,
                cost: 25,
            },
            {
                id: 3,
                title: 'Push Notifications',
                subtitle: null,
                icon: '/assets/bell.svg',
                iconAlt: 'outline of a bell',
                selected: false,
                cost: 25,
            },
        ],
        active: false,
    },
    {
        id: 5,
        title: 'What type of custom features do you expect to need?',
        subtitle: 'Select one.',
        options: [
            {
                id: 1,
                title: 'Low Complexity',
                subtitle: '(Informational)',
                icon: '/assets/info.svg',
                iconAlt: "'i' inside a circle",
                selected: false,
                cost: 25,
            },
            {
                id: 2,
                title: 'Medium Complexity',
                subtitle: '(Interactive, Customizable, Realtime)',
                icon: '/assets/customized.svg',
                iconAlt: 'two toggle switches',
                selected: false,
                cost: 50,
            },
            {
                id: 3,
                title: 'High Complexity',
                subtitle: '(Data Modeling and Computation)',
                icon: '/assets/data.svg',
                iconAlt: 'outline of line graph',
                selected: false,
                cost: 100,
            },
        ],
        active: false,
    },
    {
        id: 6,
        title: 'How many users do you expect?',
        subtitle: 'Select one.',
        options: [
            {
                id: 1,
                title: '0-50',
                subtitle: null,
                icon: '/assets/person.svg',
                iconAlt: 'person outline',
                selected: false,
                cost: 1,
            },
            {
                id: 2,
                title: '50-100',
                subtitle: null,
                icon: '/assets/persons.svg',
                iconAlt: 'outline of two people',
                selected: false,
                cost: 1.25,
            },
            {
                id: 3,
                title: '100+',
                subtitle: null,
                icon: '/assets/people.svg',
                iconAlt: 'outline of three people',
                selected: false,
                cost: 1.5,
            },
        ],
        active: false,
    },
];

const websiteQuestions = [
    { ...defaultQuestions[0], active: false },
    {
        id: 2,
        title: 'Which type of website are you wanting?',
        subtitle: 'Select one.',
        options: [
            {
                id: 1,
                title: 'Basic',
                subtitle: '(Informational)',
                icon: '/assets/info.svg',
                iconAlt: 'person outline',
                selected: false,
                cost: 100,
            },
            {
                id: 2,
                title: 'Interactive',
                subtitle: "(Users, API's, Messaging)",
                icon: '/assets/customized.svg',
                iconAlt: 'outline of two people',
                selected: false,
                cost: 200,
            },
            {
                id: 3,
                title: 'E-Commerce',
                subtitle: '(Sales)',
                icon: '/assets/globe.svg',
                iconAlt: 'outline of three people',
                selected: false,
                cost: 250,
            },
        ],
        active: true,
    },
];

export { defaultQuestions, softwareQuestions, websiteQuestions };
